# Generated by Django 5.0.1 on 2024-02-13 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statuses", "0001_initial"),
        ("tasks", "0002_rename_performer_task_executor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="statuses.status"
            ),
        ),
    ]
