# Generated by Django 5.0.1 on 2024-02-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0001_initial"),
        ("tasks", "0004_alter_task_author_alter_task_executor"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(to="labels.label"),
        ),
    ]
