# Generated by Django 5.0.2 on 2024-02-26 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0002_alter_label_name"),
        ("tasks", "0008_alter_task_executor_alter_task_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="executor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="authored_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Executor",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(
                blank=True, null=True, to="labels.label", verbose_name="Labels"
            ),
        ),
    ]
