# Generated by Django 5.0.2 on 2024-02-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statuses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Name"),
        ),
    ]
